#!/usr/bin/env python3
# Mostly auto-generated by llm to allow nightly
# NOTE: If DEPS uses Var() this will fail, as we don't exec DEPS file
import ast
import json
import subprocess
import sys
import urllib.request

if len(sys.argv) < 2:
    print("Usage: python3 gen-skia-externals.py <SKIA_TAG>")
    print("Example: python3 gen-skia-externals.py m135-0.97.2")
    sys.exit(1)

tag = sys.argv[1]
deps_url = f"https://raw.githubusercontent.com/rust-skia/skia/{tag}/DEPS"
print(f"Fetching DEPS from {deps_url}...")
try:
    deps_content = urllib.request.urlopen(deps_url).read().decode("utf-8")
except (OSError, UnicodeDecodeError) as e:
    print(f"Failed to download DEPS for tag {tag}: {e}")
    sys.exit(1)

# Parse as an AST instead of exec()'ing it - this never runs any code,
# it only builds a syntax tree we can walk.
try:
    tree = ast.parse(deps_content, filename="DEPS")
except SyntaxError as e:
    print(f"DEPS file is not valid Python syntax: {e}")
    sys.exit(1)

deps_dict_node = None
for node in tree.body:
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "deps":
                deps_dict_node = node.value
                break
    if deps_dict_node is not None:
        break

if deps_dict_node is None or not isinstance(deps_dict_node, ast.Dict):
    print("Could not find a literal 'deps' dict assignment in DEPS file.")
    sys.exit(1)

raw_deps = {}
for key_node, value_node in zip(deps_dict_node.keys, deps_dict_node.values):
    if key_node is None:
        continue  # e.g. a dict-unpacking entry, not a plain key
    try:
        key = ast.literal_eval(key_node)
    except (ValueError, TypeError, SyntaxError) as e:
        print(f"Could not parse key in DEPS file: {e}")
        continue
    try:
        # literal_eval only accepts literal Python (str/int/dict/list/etc.)
        # - it will raise on anything like Var("x") or string concatenation,
        # rather than silently executing or mis-parsing it.
        raw_deps[key] = ast.literal_eval(value_node)
    except (ValueError, TypeError, SyntaxError):
        print(f"    Skipping non-literal entry (can't statically resolve): {key}")

externals = {}
for path, spec in raw_deps.items():
    if not path.startswith("third_party/externals/"):
        continue
    name = path.replace("third_party/externals/", "")
    url, rev = None, None
    if isinstance(spec, str):
        if "@" in spec:
            url, rev = spec.split("@", 1)
    elif isinstance(spec, dict):
        url = spec.get("url")
        if url and "@" in url:
            url, rev = url.split("@", 1)
        else:
            rev = spec.get("rev")
    if not url or not rev:
        continue
    print(f"--> Prefetching: {name} ({url} @ {rev[:7]})...")
    cmd = ["nix-prefetch-git", "--url", url, "--rev", rev, "--quiet"]
    res = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if res.returncode == 0:
        data = json.loads(res.stdout)
        externals[name] = {
            "url": url,
            "rev": rev,
            "sha256": data["sha256"],
            "fetchSubmodules": False,
        }
    else:
        print(f"    Failed to prefetch {name}: {res.stderr.strip()}")

with open("skia-externals.json", "w") as f:
    json.dump(externals, f, indent=2)

print("\nSuccessfully generated skia-externals.json!")
